apiVersion: v1
kind: Service
metadata:
  name: {{ include "transfer-api.fullname" . }}
  labels:
    {{- include "transfer-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "transfer-api.selectorLabels" . | nindent 4 }}{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "transfer-api.serviceAccountName" . }}
  labels:
    {{- include "transfer-api.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
  {{- end }}