{
 "title": "Метрики bankapp",
 "tags": [ "bankapp" ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Логины пользователей (за 5м)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "increase(user_login_success_total[5m])",
     "legendFormat": "успешных логинов"
    },
    {
     "expr": "increase(user_login_failure_total[5m])",
     "legendFormat": "неуспешных логинов"
    }
   ]
  },
  {
   "title": "Неуспешные переводы (за 5м)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "increase(transfer_failure_total[5m])",
     "legendFormat": "неуспешных переводов"
    }
   ]
  },
  {
   "title": "Заблокировано операций (за 10м)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "sum(increase(transfer_blocker_total[10m])) + sum(increase(cash_blocker_total[10m]))",
     "legendFormat": "заблокировано операций"
    }
   ]
  },
  {
   "title": "Сбой отправки уведомлений (за 5м)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "increase(notifications_failure_total[5m])",
     "legendFormat": "не отправлено уведомлений"
    }
   ]
  },
  {
   "title": "Обновления курсов валют (за 10м)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 34, "h": 6 },
   "targets": [
    {
     "expr": "increase(currency_update_total[10m])",
     "legendFormat": "обновлений"
    }
   ]
  }
 ]
}