server:
  port: 8085

management:
  zipkin:
    tracing:
      #endpoint:  http://127.0.0.1:9411/api/v2/spans
      endpoint: ${ZIPKIN_URL:http://127.0.0.1:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 0.03
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: exchange-generator
  kafka:
    admin:
      auto-create: true

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8089/realms/bank
        registration:
          keycloak:
            provider: keycloak
            client-id: exchange-generator
            client-secret: KFkcoWi5ygHvZeudTTt06ShOtZ3BgMj8
            scope: profile
            authorizationGrantType: client_credentials
            clientAuthenticationMethod: client_secret_post

message:
  text: сообщение из yaml

resilience4j:
  circuitbreaker:
    instances:
      cbservice:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3