apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch.serviceAccountName" . }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
annotations:
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}