apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports:
              {{- range .Values.service.ports }}
              - name: {{ .name }}
                containerPort: {{ .targetPort }}
              {{- end }}
            volumeMounts:
              - name: pipelines
                mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: pipelines
          configMap:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-pipelines