apiVersion: v1
kind: Service
metadata:
  name: "bank-app-logstash"
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  ports:
      {{- range .Values.service.ports }}
        - name: {{ .name }}
        port: {{ .port }}
        targetPort: {{ .targetPort }}
    {{- end }}