apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-app-grafana-provisioning
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |
  {{ .Files.Get "files/provisioning/datasources/datasources.yml" | nindent 4 }}
dashboards.yaml: |
  {{ .Files.Get "files/provisioning/dashboards/dashboards.yml" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bank-app-grafana-dashboards
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
data:
  business-metrics-dashboard.json: |
  {{ .Files.Get "files/dashboards/business-metrics-dashboard.json" | nindent 4 }}
spring-boot.json: |
  {{ .Files.Get "files/dashboards/spring-boot.json" | nindent 4 }}