image:
  repository: elasticsearch
  tag: "8.12.0"

service:
  type: ClusterIP
  port: 9200
  selectorApp: bank-app-elasticsearch

serviceAccount:
  create: true
  annotations: {}
  automount: true

ingress:
  enabled: false

autoscaling:
  enabled: false

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

env:
  - name: discovery.type
    value: single-node
  - name: xpack.security.enabled
    value: "false"
  - name: network.host
    value: "0.0.0.0"
  - name: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"